// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArG8ui95jmArDFsDVz-dsCvxlmQykOJJM',
    appId: '1:224569902198:web:02e6a69f4fa9ebcb410b57',
    messagingSenderId: '224569902198',
    projectId: 'chio-app-7964a',
    authDomain: 'chio-app-7964a.firebaseapp.com',
    storageBucket: 'chio-app-7964a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB55X6ut_6HQoGpKGjHT1Wrywxtv3fS1Mg',
    appId: '1:224569902198:android:738b23ebdd05ad52410b57',
    messagingSenderId: '224569902198',
    projectId: 'chio-app-7964a',
    storageBucket: 'chio-app-7964a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArG8ui95jmArDFsDVz-dsCvxlmQykOJJM',
    appId: '1:224569902198:web:17af9cfd00a4a8a7410b57',
    messagingSenderId: '224569902198',
    projectId: 'chio-app-7964a',
    authDomain: 'chio-app-7964a.firebaseapp.com',
    storageBucket: 'chio-app-7964a.firebasestorage.app',
  );
}
